// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjXiN6OHuf6uPPqWd_LzMtJ8taNTXGCrQ',
    appId: '1:288319570838:web:53d091ce67faaf066513b7',
    messagingSenderId: '288319570838',
    projectId: 'cha-casa-nova-5e05d',
    authDomain: 'cha-casa-nova-5e05d.firebaseapp.com',
    storageBucket: 'cha-casa-nova-5e05d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrXueyK-gE5lbr3SjCblY5Iq7k-7Mt6iU',
    appId: '1:288319570838:android:af16d537747397426513b7',
    messagingSenderId: '288319570838',
    projectId: 'cha-casa-nova-5e05d',
    storageBucket: 'cha-casa-nova-5e05d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt2ZIK_ntKXA5GoTKwSLbhtJxcWTxEeHk',
    appId: '1:288319570838:ios:23585ab0248c96d86513b7',
    messagingSenderId: '288319570838',
    projectId: 'cha-casa-nova-5e05d',
    storageBucket: 'cha-casa-nova-5e05d.appspot.com',
    iosBundleId: 'com.niksoft.chaCasaNova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt2ZIK_ntKXA5GoTKwSLbhtJxcWTxEeHk',
    appId: '1:288319570838:ios:23585ab0248c96d86513b7',
    messagingSenderId: '288319570838',
    projectId: 'cha-casa-nova-5e05d',
    storageBucket: 'cha-casa-nova-5e05d.appspot.com',
    iosBundleId: 'com.niksoft.chaCasaNova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjXiN6OHuf6uPPqWd_LzMtJ8taNTXGCrQ',
    appId: '1:288319570838:web:21e0fb767ec4c4ca6513b7',
    messagingSenderId: '288319570838',
    projectId: 'cha-casa-nova-5e05d',
    authDomain: 'cha-casa-nova-5e05d.firebaseapp.com',
    storageBucket: 'cha-casa-nova-5e05d.appspot.com',
  );
}
